// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmbbW_dAT1z4lZYUhd7-jPjrXNYSzVB3I',
    appId: '1:598448920884:web:b99e734af47cd6af122d61',
    messagingSenderId: '598448920884',
    projectId: 'healthfluence-ea138',
    authDomain: 'healthfluence-ea138.firebaseapp.com',
    storageBucket: 'healthfluence-ea138.firebasestorage.app',
    measurementId: 'G-B8BX4FL7TV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcN80Ts3z1Bj8RzgyuSr0PAI-BkvAYjy4',
    appId: '1:598448920884:android:f668d6688504fa59122d61',
    messagingSenderId: '598448920884',
    projectId: 'healthfluence-ea138',
    storageBucket: 'healthfluence-ea138.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPEqaVjqIF06YRkZnkrGLZLavLzAKFch4',
    appId: '1:598448920884:ios:87dd9ef3b17cf663122d61',
    messagingSenderId: '598448920884',
    projectId: 'healthfluence-ea138',
    storageBucket: 'healthfluence-ea138.firebasestorage.app',
    iosBundleId: 'com.yuri.healthfluence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPEqaVjqIF06YRkZnkrGLZLavLzAKFch4',
    appId: '1:598448920884:ios:87dd9ef3b17cf663122d61',
    messagingSenderId: '598448920884',
    projectId: 'healthfluence-ea138',
    storageBucket: 'healthfluence-ea138.firebasestorage.app',
    iosBundleId: 'com.yuri.healthfluence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmbbW_dAT1z4lZYUhd7-jPjrXNYSzVB3I',
    appId: '1:598448920884:web:86e0eb04144bde57122d61',
    messagingSenderId: '598448920884',
    projectId: 'healthfluence-ea138',
    authDomain: 'healthfluence-ea138.firebaseapp.com',
    storageBucket: 'healthfluence-ea138.firebasestorage.app',
    measurementId: 'G-QDW8LJ4129',
  );
}
